package com.acumedicalinc.web.entity;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * 
 * @author JC
 * 
 * table entry for entries of format A
 * 	format A:
 * 		9 columns; 
 * 			1st column = time, 
 * 			column 2-9 = channel data
 *
 */
@Entity
@Table(name = "RawDataFormatA")
public class FormA implements Serializable {
	private static final long serialVersionUID = 1L;

	public FormA(){
	}
		
	//Id in table, unique for each entry. Autogenerated.
	@Id
	@GenericGenerator(name="generator", strategy="increment")
	@GeneratedValue(generator="generator")
	@Column(name = "id", unique = true)
	private Long id;
	
	//1st column in raw data file
	@Column
	private Long time;
	
	//2nd-9th columns in raw data file
	//Channels 1-8, may change names later
	@Column
	private Long channel1;
	@Column
	private Long channel2; 
	@Column
	private Long channel3;
	@Column
	private Long channel4;
	@Column
	private Long channel5;
	@Column
	private Long channel6;
	@Column
	private Long channel7;
	@Column
	private Long channel8;
	
	//time stamp, same for each row in a file, taken from file name
	@Column
	private String timestamp;
	
	public Long getId() {
		return id;
	}
	
	public void setTime(long t){
		time = t;
	}
	
	public void setData(long[] d){
		d[0] = channel1;
		d[1] = channel2;
		d[2] = channel3;
		d[3] = channel4;
		d[4] = channel5;
		d[5] = channel6;
		d[6] = channel7;
		d[7] = channel8;
	}
	
	public void setTimestamp(String ts){
		timestamp = ts;
	}
	
}
